sudo: false

language: scala
scala:
  - 2.13.0
  - 2.12.9

dist: xenial
services:
  - xvfb

jdk:
  - oraclejdk11
  - oraclejdk12
  - openjdk11
  - openjdk12

branches:
  only:
    - master

install: true

script:
  - java -version
  - sbt test

